postgresql:
  podLabels:
    branch: $BRANCH_LC
    resource: pod
    team: napps
    usage: utests
  master:
    labels:
      branch: "$BRANCH_LC"
      resource: deployment
      team: napps
      usage: utests
    tolerations:
    - key: team
      operator: Equal
      value: napps
      effect: NoSchedule
    nodeSelector:
      team: napps
  resources:
    requests:
      cpu: 500m
      memory: 250Mi
    limits:
      cpu: 1
      memory: 500Mi
tags:
  postgresql: true
